# SPDX-FileCopyrightText: Copyright The Moby Authors
# SPDX-License-Identifier: Apache-2.0
# Task-specific derivative; source Docker 29.8.1 commit 464cd50.
# profile generated by github.com/moby/profiles/apparmor.
abi <abi/3.0>,
#include <tunables/global>

profile "bokkie-bwrap-hj3yyjlo" flags=(attach_disconnected,mediate_deleted) {
  #include <abstractions/base>
  network,
  # Disallow AF_ALG (Linux kernel crypto API); see https://copy.fail/
  deny network alg,
  # Disallow AF_VSOCK to prevent host/guest communication.
  deny network vsock,
  capability,
  file,
  umount,
  # Host (privileged) processes may send signals to container processes.
  signal (receive) peer=unconfined,
  # runc may send signals to container processes (for "docker stop").
  signal (receive) peer=runc,
  # crun may send signals to container processes (for "docker stop" when used with crun OCI runtime).
  signal (receive) peer=crun,
  # dockerd may send signals to container processes (for "docker kill").
  signal (receive) peer="unconfined",
  # Container processes may send signals amongst themselves.
  signal (send,receive) peer="bokkie-bwrap-hj3yyjlo",

  deny @{PROC}/* w,   # deny write for all files directly in /proc (not in a subdir)
  # deny write to files not in /proc/<number>/** or /proc/sys/**
  deny @{PROC}/{[^1-9/],[^1-9/][^0-9/],[^1-9s/][^0-9y/][^0-9s/],[^1-9/][^0-9/][^0-9/][^0-9/]*}/** w,
  deny @{PROC}/sys/[^k]** w,  # deny /proc/sys except /proc/sys/k* (effectively /proc/sys/kernel)
  deny @{PROC}/sys/kernel/{?,??,[^s][^h][^m]**} w,  # deny everything except shm* in /proc/sys/kernel/
  deny @{PROC}/sysrq-trigger rwklx,
  deny @{PROC}/kcore rwklx,

  # Only the observed Bubblewrap propagation operation is admitted.
  mount options=(rslave,silent) -> /,
  mount fstype=tmpfs options=(rw,nosuid,nodev) -> /newroot/dev/,
  mount options=(rw,rbind,silent) /oldroot/dev/null -> /newroot/dev/null,
  mount options=(rw,rbind,silent) /oldroot/dev/zero -> /newroot/dev/zero,
  mount options=(rw,rbind,silent) /oldroot/dev/full -> /newroot/dev/full,
  mount options=(rw,rbind,silent) /oldroot/dev/random -> /newroot/dev/random,
  mount options=(rw,rbind,silent) /oldroot/dev/urandom -> /newroot/dev/urandom,
  mount options=(rw,rbind,silent) /oldroot/dev/tty -> /newroot/dev/tty,
  mount fstype=devpts options=(rw,nosuid,noexec) -> /newroot/dev/pts/,
  mount fstype=proc options=(rw,nosuid,nodev,noexec) -> /newroot/proc/,
  mount options=(ro,nosuid,nodev,remount,bind,silent) -> /newroot{,/**},
  mount options=(ro,nosuid,nodev,remount,bind,silent,relatime) -> /newroot{,/**},
  mount options=(ro,nosuid,nodev,noexec,remount,bind,silent,relatime) -> /newroot{,/**},
  mount options=(rw,rbind,silent) /oldroot/ -> /newroot/,
  pivot_root oldroot=/tmp/oldroot/ /tmp/,
  mount options=(rw,rbind,silent) /tmp/newroot/ -> /tmp/newroot/,
  mount fstype=tmpfs options=(rw,nosuid,nodev) -> /tmp/,

  deny /sys/[^f]*/** wklx,
  deny /sys/f[^s]*/** wklx,
  deny /sys/fs/[^c]*/** wklx,
  deny /sys/fs/c[^g]*/** wklx,
  deny /sys/fs/cg[^r]*/** wklx,
  deny /sys/firmware/** rwklx,
  deny /sys/devices/virtual/powercap/** rwklx,
  deny /sys/kernel/security/** rwklx,

  # allow processes within the container to trace each other,
  # provided all other LSM and yama setting allow it.
  ptrace (trace,tracedby,read,readby) peer="bokkie-bwrap-hj3yyjlo",
}
